### ISSUE TITLE
When i am trying to intialise the configureHumanID in index.js getting errors

### ISSUE THREAD

**Issue by pm-sharma** [bluenumberfoundation/humanid-reactnative-sdk#2]
import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';

import {configureHumanID} from "@human-id/react-native-humanid";  
import AppLogo from "./src/assets/AppLogo.js";
import {HUMANID_SECRET, HUMANID_CLIENTID} from "@env"

configureHumanID({  
    appName: "APPNAME",
    clientSecret: HUMANID_SECRET,
    clientId: HUMANID_CLIENTID,
    Icon: AppLogo 
});
  
AppRegistry.registerComponent(appName, () => App);

![Screenshot 2021-05-21 at 6 54 22 PM](https://user-images.githubusercontent.com/41280402/119145736-8d4d8e00-ba67-11eb-8712-196b15dc9078.png)

**Comment by bobbyecho** [comment]
> import {AppRegistry} from 'react-native';
> import App from './App';
> import {name as appName} from './app.json';
> 
> import {configureHumanID} from "@human-id/react-native-humanid";
> import AppLogo from "./src/assets/AppLogo.js";
> import {HUMANID_SECRET, HUMANID_CLIENTID} from "@env"
> 
> configureHumanID({
> appName: "APPNAME",
> clientSecret: HUMANID_SECRET,
> clientId: HUMANID_CLIENTID,
> Icon: AppLogo
> });
> 
> AppRegistry.registerComponent(appName, () => App);
> 
> ![Screenshot 2021-05-21 at 6 54 22 PM](https://user-images.githubusercontent.com/41280402/119145736-8d4d8e00-ba67-11eb-8712-196b15dc9078.png)

Hi @pm-sharma, sorry for being late reply

this is about autolinking issue on IOS, fixed on the latest version

please upgrade version of @humanid/react-native-humanid into <b>v2.3.1</b>

let me know if there is any more issue, thanks :beer:

**Comment by pm-sharma** [comment]
Yes, Working thank you
