### ISSUE TITLE
Font unrecognised

### ISSUE THREAD

**Issue by pm-sharma** [bluenumberfoundation/humanid-reactnative-sdk#3]
I have also the font to my info.plist file.
Like this: `<key>UIAppFonts</key>
	<array>
		<string>Lato-Bold.ttf</string>
		<string>Lato-Regular.ttf</string>
		<string>Lato-Thin.ttf</string>
		<string>Roboto-Bold.ttf</string>
		<string>Roboto-Light.ttf</string>
		<string>Roboto-Regular.ttf</string>
		<string>Montserrat-Medium.ttf</string>
		<string>Montserrat-Regular.ttf</string>
	</array>`

![Simulator Screen Shot - iPhone 12 - 2021-06-07 at 21 12 34](https://user-images.githubusercontent.com/41280402/121049318-3a006d00-c7d5-11eb-82e1-e8e0d62cfee8.png)

**Comment by bobbyecho** [comment]
hi @pm-sharma , did you hit `npx react-native link` after installation? asset will link automatically with this command.

**Comment by bobbyecho** [comment]
@pm-sharma in case you already hit 'npx react-native link' but still getting this issue, could you please open .xworkspace and drop a screenshoot the expanded resource folder on that ios project

**Comment by bobbyecho** [comment]
closed temporary due inactivity

**Comment by pm-sharma** [comment]
I am using the latest version of react and react native so the react-native link is not required and do I need add font manually here ?

![Screenshot 2021-08-18 at 2 01 49 AM](https://user-images.githubusercontent.com/41280402/129796477-be634b90-103d-4480-8ebc-bb4962491c6a.png)

**Comment by pm-sharma** [comment]
@bobbyecho please check

**Comment by pm-sharma** [comment]
When I clicking to button nothing happening

![Simulator Screen Shot - iPhone 12 - 2021-08-18 at 02 18 41](https://user-images.githubusercontent.com/41280402/129798481-90ca9cdc-b287-40a8-9028-4d686e9b702c.png)
